### ISSUE TITLE
1906-03-22

### ISSUE THREAD

**Issue by kml18f** [dig-eg-gaz/page-images#70]
![1906-03-22-p1](https://user-images.githubusercontent.com/59891453/76671543-4fa0cb80-656d-11ea-9107-4341e2746434.jpg)
![1906-03-22-p2](https://user-images.githubusercontent.com/59891453/76671548-52032580-656d-11ea-81e0-3471bd76ccba.jpg)
![1906-03-22-p3](https://user-images.githubusercontent.com/59891453/76671550-53cce900-656d-11ea-982a-314e721611bc.jpg)
![1906-03-22-p4](https://user-images.githubusercontent.com/59891453/76671553-562f4300-656d-11ea-82dc-aaceac7423f1.jpg)
![1906-03-22-p5](https://user-images.githubusercontent.com/59891453/76671555-58919d00-656d-11ea-9019-33c7c54b953d.jpg)
![1906-03-22-p6](https://user-images.githubusercontent.com/59891453/76671556-5b8c8d80-656d-11ea-8e09-1a7250209093.jpg)
![1906-03-22-p7](https://user-images.githubusercontent.com/59891453/76671559-5deee780-656d-11ea-8979-19e7fda346d6.jpg)
![1906-03-22-p8](https://user-images.githubusercontent.com/59891453/76671566-60514180-656d-11ea-812a-c050d5862958.jpg)

**Comment by whanley** [comment]
These images are now in the repository.
